# Generated by Django 3.2 on 2021-05-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_card_cardproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('progress', 'Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='created', max_length=10),
        ),
    ]
