# Generated by Django 3.2 on 2021-04-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
