# Generated by Django 3.2 on 2021-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_card_cardproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
