# Generated by Django 3.2 on 2021-05-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_card_status'),
        ('shop', '0003_review'),
    ]

    operations = [
    ]
