# Generated by Django 3.2 on 2021-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210430_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='count',
            field=models.IntegerField(),
        ),
    ]
