# Generated by Django 3.2 on 2021-04-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_name'),
        ('shop', '0003_rename_image_productimage'),
    ]

    operations = [
    ]
